import {defineField, defineType} from 'sanity';

export const indexPageType = defineType({
  type: 'document',
  name: 'indexPage',
  title: 'Main Page',
  description: '',
  fields: [
    defineField({
      name: 'metaType',
      type: 'string',
      title: 'Meta Type',
      hidden: false,
      description: '(optional)',
    }),
    defineField({
      name: 'metaTitle',
      type: 'string',
      title: 'Meta Title',
      hidden: false,
      description: '(optional)',
    }),
    defineField({
      name: 'metaDescription',
      type: 'string',
      title: 'Meta Description',
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'metaKeywords',
      type: 'array',
      of: [{type: 'string'}],
      title: 'Meta Keywords',
      hidden: false,
      options: {layout: 'tags'},
    }),
    defineField({
      name: 'metaImage',
      type: 'image',
      title: 'Meta Image',
      hidden: false,
      description: '(optional)',
    }),
    defineField({
      name: 'name',
      type: 'string',
      title: 'Name',
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'title',
      type: 'string',
      title: 'Title',
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'identifier',
      type: 'slug',
      title: 'Identifier',
      hidden: false,
      validation: (Rule) => Rule.required(),
      options: {source: 'name'},
    }),
    defineField({
      name: 'h1',
      type: 'string',
      title: 'H1',
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'h1Image',
      type: 'image',
      title: 'H1 Image',
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'signupFormInputPlaceholder',
      type: 'string',
      title: 'Signup Form Input Placeholder',
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'signupFormCta',
      type: 'string',
      title: 'Signup Form CTA',
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'signupFormUrl',
      type: 'string',
      title: 'Signup Form URL',
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'signupFormGroupId',
      type: 'string',
      title: 'Signup Form Group ID',
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'mainPageBanner',
      type: 'reference',
      title: 'Main Page Banner',
      hidden: false,
      to: [{type: 'indexPageBanner'}],
    }),
    defineField({
      type: 'boolean',
      description:
        'If this document was archived on Contentful at the time of export, the document will be in a read-only state.',
      name: 'contentfulArchived',
      readOnly: true,
    }),
  ],
  preview: {select: {title: 'name'}},
  readOnly: ({document}) => (document == null ? void 0 : document.contentfulArchived) === !0,
});
