import {defineField, defineType} from 'sanity';

export const innerContentSwitcherType = defineType({
  type: 'document',
  name: 'innerContentSwitcher',
  title: 'Inner Content Switcher',
  description: '',
  fields: [
    defineField({
      name: 'title',
      type: 'string',
      title: 'Title',
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'desktopContent',
      type: 'array',
      of: [
        {
          type: 'block',
          styles: [
            {title: 'Heading 2', value: 'h2'},
            {title: 'Heading 3', value: 'h3'},
            {title: 'Heading 4', value: 'h4'},
            {title: 'Heading 5', value: 'h5'},
            {title: 'Heading 6', value: 'h6'},
            {title: 'Quote', value: 'blockquote'},
          ],
          lists: [
            {title: 'Bullet', value: 'bullet'},
            {title: 'Numbered', value: 'number'},
          ],
          marks: {
            decorators: [
              {title: 'Strong', value: 'strong'},
              {title: 'Emphasis', value: 'em'},
              {title: 'Underline', value: 'underline'},
            ],
            annotations: [
              {
                type: 'object',
                name: 'link',
                title: 'url',
                fields: [
                  defineField({
                    type: 'string',
                    name: 'href',
                    title: 'URL',
                    validation: (Rule) => Rule.required(),
                  }),
                  defineField({
                    type: 'string',
                    name: 'target',
                    title: 'Target',
                    options: {
                      list: [
                        {value: '_blank', title: 'Blank'},
                        {value: '_parent', title: 'Parent'},
                      ],
                    },
                  }),
                ],
              },
              {
                type: 'reference',
                name: 'reference',
                title: 'Reference',
                to: [
                  {type: 'navigation'},
                  {type: 'navigationElement'},
                  {type: 'navigationSubmenu'},
                  {type: 'post'},
                  {type: 'person'},
                  {type: 'header'},
                  {type: 'logo'},
                  {type: 'footer'},
                  {type: 'socialBar'},
                  {type: 'socialIcon'},
                  {type: 'popularArticles'},
                  {type: 'deploy'},
                  {type: 'indexPage'},
                  {type: 'indexPageBanner'},
                  {type: 'postPageBanner'},
                  {type: 'customScripts'},
                  {type: 'script'},
                  {type: 'blogPostEmbeddedVideo'},
                  {type: 'postBanner'},
                  // {type: 'jumpLink'},
                  {type: 'contentTable'},
                  {type: 'commonPaywall'},
                  {type: 'pricing'},
                  {type: 'blogPostMobileBanner'},
                  {type: 'blogPostEmbeddedAutoVideo'},
                  {type: 'collectPanem'},
                  {type: 'inlineLink'},
                  {type: 'postListAdditionalBanners'},
                  {type: 'blogPostWebinarBanner'},
                  {type: 'watchTutorial'},
                  {type: 'blogPostSchema'},
                  {type: 'innerContentSwitcher'},
                ],
              },
              {type: 'image'},
              {type: 'file'},
            ],
          },
        },
        {type: 'break'},
      ],
      title: 'Desktop Content',
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'mobileContent',
      type: 'array',
      of: [
        {
          type: 'block',
          styles: [
            {title: 'Heading 2', value: 'h2'},
            {title: 'Heading 3', value: 'h3'},
            {title: 'Heading 4', value: 'h4'},
            {title: 'Heading 5', value: 'h5'},
            {title: 'Heading 6', value: 'h6'},
            {title: 'Quote', value: 'blockquote'},
          ],
          lists: [
            {title: 'Bullet', value: 'bullet'},
            {title: 'Numbered', value: 'number'},
          ],
          marks: {
            decorators: [
              {title: 'Strong', value: 'strong'},
              {title: 'Emphasis', value: 'em'},
              {title: 'Underline', value: 'underline'},
            ],
            annotations: [
              {
                type: 'object',
                name: 'link',
                title: 'url',
                fields: [
                  defineField({
                    type: 'string',
                    name: 'href',
                    title: 'URL',
                    validation: (Rule) => Rule.required(),
                  }),
                  defineField({
                    type: 'string',
                    name: 'target',
                    title: 'Target',
                    options: {
                      list: [
                        {value: '_blank', title: 'Blank'},
                        {value: '_parent', title: 'Parent'},
                      ],
                    },
                  }),
                ],
              },
              {
                type: 'reference',
                name: 'reference',
                title: 'Reference',
                to: [
                  {type: 'navigation'},
                  {type: 'navigationElement'},
                  {type: 'navigationSubmenu'},
                  {type: 'post'},
                  {type: 'person'},
                  {type: 'header'},
                  {type: 'logo'},
                  {type: 'footer'},
                  {type: 'socialBar'},
                  {type: 'socialIcon'},
                  {type: 'popularArticles'},
                  {type: 'deploy'},
                  {type: 'indexPage'},
                  {type: 'indexPageBanner'},
                  {type: 'postPageBanner'},
                  {type: 'customScripts'},
                  {type: 'script'},
                  {type: 'blogPostEmbeddedVideo'},
                  {type: 'postBanner'},
                  // {type: 'jumpLink'},
                  {type: 'contentTable'},
                  {type: 'commonPaywall'},
                  {type: 'pricing'},
                  {type: 'blogPostMobileBanner'},
                  {type: 'blogPostEmbeddedAutoVideo'},
                  {type: 'collectPanem'},
                  {type: 'inlineLink'},
                  {type: 'postListAdditionalBanners'},
                  {type: 'blogPostWebinarBanner'},
                  {type: 'watchTutorial'},
                  {type: 'blogPostSchema'},
                  {type: 'innerContentSwitcher'},
                ],
              },
              {type: 'image'},
              {type: 'file'},
            ],
          },
        },
        {type: 'break'},
      ],
      title: 'Mobile Content',
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      type: 'boolean',
      description:
        'If this document was archived on Contentful at the time of export, the document will be in a read-only state.',
      name: 'contentfulArchived',
      readOnly: true,
    }),
  ],
  preview: {select: {title: 'title'}},
  readOnly: ({document}) => (document == null ? void 0 : document.contentfulArchived) === !0,
});
