import {defineField, defineType} from 'sanity'
import {validateIn} from './validation'

export const postType = defineType({
  type: 'document',
  name: 'post',
  title: 'Blog Post',
  description: '',
  fields: [
    defineField({
      name: 'localizations',
      type: 'array',
      of: [
        {
          type: 'string',
          validation: (Rule) => Rule.custom((value) => validateIn(['en-US', 'de'], value)),
          options: {list: ['en-US', 'de']},
        },
      ],
      title: 'Localizations',
      hidden: false,
      validation: (Rule) => Rule.required(),
      options: {
        list: [
          {value: 'en-US', title: 'en-US'},
          {value: 'de', title: 'de'},
        ],
      },
    }),
    defineField({
      name: 'metaTitle',
      type: 'string',
      title: 'Meta Title',
      hidden: false,
      description: '(optional)',
    }),
    defineField({
      name: 'metaType',
      type: 'string',
      title: 'Meta Type',
      hidden: false,
      description: '(optional)',
    }),
    defineField({
      name: 'metaUrl',
      type: 'string',
      title: 'Meta Url',
      hidden: false,
      description: '(optional)',
    }),
    defineField({
      name: 'metaDescription',
      type: 'string',
      title: 'Meta Description',
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'metaKeywords',
      type: 'array',
      of: [{type: 'string'}],
      title: 'Meta Keywords',
      hidden: false,
      options: {layout: 'tags'},
    }),
    defineField({
      name: 'metaImage',
      type: 'image',
      title: 'Meta Image',
      hidden: false,
      description: '(optional)',
    }),
    defineField({
      name: 'structuredData',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'blogPostSchema'}]}],
      title: 'Structured Data',
      hidden: false,
      validation: (Rule) => Rule.min(0),
    }),
    defineField({
      name: 'name',
      type: 'string',
      title: 'Name',
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'title',
      type: 'string',
      title: 'Title',
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      hidden: false,
      validation: (Rule) => Rule.required(),
      options: {source: 'name'},
    }),
    defineField({
      name: 'heroImage',
      type: 'image',
      title: 'Hero Image',
      hidden: false,
      description: 'Recommended size: 1456x560px ',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'imagePreview',
      type: 'image',
      title: 'Image Preview',
      hidden: false,
      description: 'Recommended size: 112x112px',
    }),
    defineField({
      name: 'h1',
      type: 'string',
      title: 'H1',
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'publishedDate',
      type: 'date',
      title: 'Published Date',
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'author',
      type: 'reference',
      title: 'Author',
      hidden: false,
      validation: (Rule) => Rule.required(),
      to: [{type: 'person'}],
    }),
    defineField({
      name: 'excerpt',
      type: 'array',
      of: [{type: 'block'}, {type: 'image'}],
      title: 'Excerpt',
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'featuredProduct',
      type: 'reference',
      title: 'Featured product',
      hidden: false,
      to: [{type: 'postBanner'}],
    }),
    defineField({
      name: 'popularArticles',
      type: 'reference',
      title: 'Popular Articles',
      hidden: false,
      description: '(optional) Please select recommended articles:',
      to: [{type: 'popularArticles'}],
    }),
    defineField({
      name: 'body',
      type: 'array',
      of: [
        {
          type: 'block',
          styles: [
            {title: 'Heading 2', value: 'h2'},
            {title: 'Heading 3', value: 'h3'},
            {title: 'Heading 4', value: 'h4'},
            {title: 'Heading 5', value: 'h5'},
            {title: 'Heading 6', value: 'h6'},
            {title: 'Quote', value: 'blockquote'},
          ],
          lists: [
            {title: 'Bullet', value: 'bullet'},
            {title: 'Numbered', value: 'number'},
          ],
          marks: {
            decorators: [
              {title: 'Strong', value: 'strong'},
              {title: 'Emphasis', value: 'em'},
              {title: 'Code', value: 'code'},
              {title: 'Underline', value: 'underline'},
            ],
            annotations: [
              {
                type: 'object',
                name: 'link',
                title: 'url',
                fields: [
                  defineField({
                    type: 'string',
                    name: 'href',
                    title: 'URL',
                    validation: (Rule) => Rule.required(),
                  }),
                  defineField({
                    type: 'string',
                    name: 'target',
                    title: 'Target',
                    options: {
                      list: [
                        {value: '_blank', title: 'Blank'},
                        {value: '_parent', title: 'Parent'},
                      ],
                    },
                  }),
                ],
              },
              {
                type: 'reference',
                name: 'reference',
                title: 'Reference',
                to: [
                  {type: 'navigation'},
                  {type: 'navigationElement'},
                  {type: 'navigationSubmenu'},
                  {type: 'post'},
                  {type: 'person'},
                  {type: 'header'},
                  {type: 'logo'},
                  {type: 'footer'},
                  {type: 'socialBar'},
                  {type: 'socialIcon'},
                  {type: 'popularArticles'},
                  {type: 'deploy'},
                  {type: 'indexPage'},
                  {type: 'indexPageBanner'},
                  {type: 'postPageBanner'},
                  {type: 'customScripts'},
                  {type: 'script'},
                  {type: 'blogPostEmbeddedVideo'},
                  {type: 'postBanner'},
                  // {type: 'jumpLink'},
                  {type: 'contentTable'},
                  {type: 'commonPaywall'},
                  {type: 'pricing'},
                  {type: 'blogPostMobileBanner'},
                  {type: 'blogPostEmbeddedAutoVideo'},
                  {type: 'collectPanem'},
                  {type: 'inlineLink'},
                  {type: 'postListAdditionalBanners'},
                  {type: 'blogPostWebinarBanner'},
                  {type: 'watchTutorial'},
                  {type: 'blogPostSchema'},
                  {type: 'innerContentSwitcher'},
                ],
              },
              {type: 'image'},
              {type: 'file'},
            ],
          },
          of: [
            {
              type: 'reference',
              title: 'Reference',
              to: [
                {type: 'inlineLink'},
                {type: 'innerContentSwitcher'},
                // {type: 'jumpLink'}
              ],
            },
          ],
        },
        {
          type: 'reference',
          title: 'Reference',
          to: [
            {type: 'postPageBanner'},
            {type: 'blogPostEmbeddedAutoVideo'},
            {type: 'blogPostEmbeddedVideo'},
            {type: 'blogPostMobileBanner'},
            {type: 'blogPostWebinarBanner'},
            {type: 'innerContentSwitcher'},
            // {type: 'jumpLink'},
            {type: 'contentTable'},
          ],
        },
        {type: 'image'},
        {type: 'file'},
        {type: 'break'},
      ],
      title: 'Body',
      hidden: false,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'collectPanelDisplay',
      type: 'boolean',
      title: 'Collect Panel Display',
      hidden: false,
      initialValue: true,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'collectPanel',
      type: 'reference',
      title: 'Collect Panel',
      hidden: false,
      validation: (Rule) => Rule.required(),
      to: [{type: 'collectPanem'}],
    }),
    defineField({
      name: 'watchTutorial',
      type: 'reference',
      title: 'Watch Tutorial',
      hidden: false,
      to: [{type: 'watchTutorial'}],
    }),
    defineField({
      type: 'boolean',
      description:
        'If this document was archived on Contentful at the time of export, the document will be in a read-only state.',
      name: 'contentfulArchived',
      readOnly: true,
    }),
  ],
  preview: {select: {title: 'name'}},
  readOnly: ({document}) => (document == null ? void 0 : document.contentfulArchived) === !0,
});
